# DataSource Config
server:
  port: 8088
  servlet:

spring:
  datasource:
      username: root
      password: 123
      url: jdbc:mysql://127.0.0.1:3306/coc?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
#    打印sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

